_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": darwin-x86_64
bins:
    value:
        - 400
        - 800
        - 1300
        - 2100
        - 3000
        - 3700
        - 4700
        - 7020
        - 9660
dropout:
    value: 0.5
epochs:
    value: 50000
gat:
    value: true
graph_num:
    value: 17
hidden_c:
    value: 350
learning_rate:
    value: 0.0001
num_heads:
    value: 1
num_layers:
    value: 2
random_seed:
    value: 100
